[package]
name = "two-factor-auth"
version = "0.1.0"
edition = "2021"
authors = ["haihuiling2014@gmail.com"]

[dependencies]
hmac-sha1 = "0.1.3"
base32 = "0.4.0"


[[bin]]
name = "2fa"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
opt-level = "z"
